# Generated by Django 5.1 on 2024-10-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
        ('work', '0002_alter_manager_options_alter_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.manager'),
        ),
    ]
