# Generated by Django 5.1 on 2024-10-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_customuser_manager_id'),
        ('work', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.manager'),
        ),
    ]
