# Generated by Django 5.1 on 2024-10-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_alter_customuser_manager_id'),
        ('work', '0007_attendance_date_info_delete_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attendance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.attendance'),
        ),
    ]
