# Generated by Django 5.1 on 2024-10-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0004_customuser_attendance'),
        ('work', '0008_alter_info_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='attendance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.info'),
        ),
    ]
