# Generated by Django 5.1 on 2024-10-11 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0008_alter_customuser_manager_id_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_number',
            field=models.IntegerField(error_messages={'unique': 'A user with that employee_number already exists.'}, max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[0-9]{6}'), django.core.validators.MinLengthValidator(6)], verbose_name='社員番号'),
        ),
    ]
