# Generated by Django 5.1 on 2024-10-19 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0010_alter_customuser_manager_id_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_number',
            field=models.IntegerField(error_messages={'unique': 'A user with that employee_number already exists.'}, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)], verbose_name='社員番号'),
        ),
    ]
