# Generated by Django 5.1 on 2024-10-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_manager_options_alter_manager_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.TimeField(verbose_name='出勤時間')),
                ('closing_time', models.TimeField(verbose_name='退勤時間')),
                ('break_time', models.TimeField(verbose_name='休憩時間')),
                ('content', models.CharField(max_length=150, verbose_name='業務内容')),
            ],
        ),
    ]
