# Generated by Django 5.1 on 2024-10-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': '勤怠状況', 'verbose_name_plural': '勤怠状況'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': '年月', 'verbose_name_plural': '年月'},
        ),
        migrations.RemoveField(
            model_name='year',
            name='attendance',
        ),
        migrations.AddField(
            model_name='year',
            name='attendance_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.attendance'),
        ),
    ]
