# Generated by Django 5.1 on 2024-10-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_attendance_options_alter_year_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='attendance_id',
            new_name='attendance',
        ),
    ]
