# Generated by Django 5.1 on 2024-10-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_rename_attendance_id_year_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True, verbose_name='出勤日'),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ManyToManyField(blank=True, to='work.attendance')),
            ],
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
