# Generated by Django 5.1 on 2024-10-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_alter_info_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='attendance',
        ),
        migrations.AddField(
            model_name='info',
            name='attendance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.attendance'),
        ),
    ]
