# Generated by Django 5.1 on 2024-10-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_remove_info_attendance_info_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='info',
            name='attendance',
        ),
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.ManyToManyField(null=True, to='work.attendance'),
        ),
    ]
