# Generated by Django 5.1 on 2024-10-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_remove_attendance_date_remove_info_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.attendance'),
        ),
        migrations.RemoveField(
            model_name='info',
            name='date',
        ),
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
    ]
