# Generated by Django 5.1 on 2024-10-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_alter_info_options_remove_info_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.ManyToManyField(blank=True, to='work.date'),
        ),
    ]
