# Generated by Django 5.1 on 2024-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_alter_info_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': '出勤日', 'verbose_name_plural': '出勤日'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '勤怠情報', 'verbose_name_plural': '勤怠情報'},
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(null=True, unique=True, verbose_name='日付'),
        ),
    ]
