# Generated by Django 5.1 on 2024-10-08 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0006_remove_customuser_attendance_remove_customuser_id_and_more'),
        ('work', '0014_alter_date_options_alter_info_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='info',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True, verbose_name='出勤日'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員番号'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee_number', 'date'), name='employee_number_date_unique'),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
