# Generated by Django 5.1 on 2024-10-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_alter_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='break_time',
            field=models.TimeField(null=True, verbose_name='休憩時間'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='closing_time',
            field=models.TimeField(null=True, verbose_name='退勤時間'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='content',
            field=models.CharField(max_length=150, null=True, verbose_name='業務内容'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='出勤日'),
        ),
    ]
