# Generated by Django 5.1 on 2024-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_alter_attendance_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='break_time',
            field=models.DurationField(null=True, verbose_name='休憩時間'),
        ),
    ]
